const fs = require('fs');

const trickyQuestions = [
    { id: 267, course: 'PMG313', topic: 'WBS vs Activity List', type: 'objective', difficulty: 'hard', question: 'Which statement best describes the relationship between the Work Breakdown Structure (WBS) and the Activity List?', options: ['A. The WBS contains activities; the Activity List contains work packages.','B. The WBS is deliverable-oriented; the Activity List is action-oriented.','C. They are identical documents used in different phases.','D. The Activity List is a subset of the WBS dictionary.'], answer: 'B', explanation: 'WBS focuses on what is being delivered (nouns), while the Activity List focuses on how it is done (verbs).' },
    { id: 268, course: 'PMG313', topic: 'Scope Validation', type: 'objective', difficulty: 'hard', question: 'A project deliverable has been completed but fails to meet one minor quality standard. However, the customer is willing to accept it as is to meet a deadline. What should the Project Manager do first?', options: ['A. Sign off on the Validate Scope process.','B. Document the non-conformity and obtain a formal sign-off on the deviation.','C. Request a Change Request to lower the quality standards globally.','D. Reject the deliverable to maintain integrity.'], answer: 'B', explanation: 'Deviations from the original requirements must be formally documented even if accepted by the customer.' },
    { id: 269, course: 'PMG313', topic: 'Scope Creep vs Progressive Elaboration', type: 'objective', difficulty: 'hard', question: 'In an Agile project, a stakeholder requests a new feature mid-sprint that was not in the initial backlog. The team decides to add it because they have extra capacity. This is an example of:', options: ['A. Progressive Elaboration','B. Scope Creep','C. Value-Added Refinement','D. Backlog Grooming'], answer: 'B', explanation: 'Adding features not in the sprint plan, even with capacity, without following the change process is creep.' },
    { id: 270, course: 'PMG313', topic: 'Requirements Traceability Matrix', type: 'objective', difficulty: 'hard', question: 'What is the PRIMARY value of a Requirements Traceability Matrix (RTM) during the Validate Scope process?', options: ['A. It tracks the cost of each requirement.','B. It ensures each requirement adds business value by linking it to objectives.','C. It provides a list of stakeholders who requested each feature.','D. It predicts future scope changes based on historical data.'], answer: 'B', explanation: 'RTM links requirements from their origin to the deliverables that satisfy them.' },
    { id: 271, course: 'PMG313', topic: 'Control Scope', type: 'objective', difficulty: 'hard', question: 'During Control Scope, the PM notices that the team is spending 20% more time on a deliverable than planned, but the scope remains unchanged. This suggests:', options: ['A. Scope Creep','B. Gold Plating','C. Inaccurate estimation or poor productivity','D. Progressive Elaboration'], answer: 'C', explanation: 'If the scope is the same, the variance is a schedule/resource issue, not a scope issue.' },
    { id: 272, course: 'PMG313', topic: 'Work Package', type: 'objective', difficulty: 'hard', question: 'A Work Package is the lowest level of the WBS. If a work package is still too complex to estimate accurately, what is the Best Practice?', options: ['A. Estimate it anyway and add a large contingency.','B. Decompose it further into smaller work packages.','C. Hire a specialist to handle that specific package.','D. Ignore it until the execution phase.'], answer: 'B', explanation: 'The goal of decomposition is to reach a level where cost and duration can be reliably estimated.' },
    { id: 273, course: 'PMG313', topic: 'Scope Baseline', type: 'objective', difficulty: 'hard', question: 'Which document contains the Agreement on what constitutes a successful project completion?', options: ['A. Project Charter','B. Project Scope Statement','C. WBS Dictionary','D. Quality Management Plan'], answer: 'B', explanation: 'The Scope Statement defines success criteria and boundaries.' },
    { id: 274, course: 'PMG313', topic: 'Scope vs Quality', type: 'objective', difficulty: 'hard', question: 'A deliverable meets all requirements in the scope statement but fails the internal stress test. The PM should focus on:', options: ['A. Validate Scope','B. Control Quality','C. Define Scope','D. Plan Resource Management'], answer: 'B', explanation: 'Meeting internal standards is a Quality issue; customer acceptance is a Scope issue.' },
    { id: 275, course: 'FIN313', topic: 'NPV vs IRR', type: 'objective', difficulty: 'hard', question: 'Project A has a higher IRR than Project B, but Project B has a higher NPV. If there is no capital rationing and the projects are mutually exclusive, which do you pick?', options: ['A. Project A, for the higher percentage return.','B. Project B, for the higher absolute wealth creation.','C. Whichever has a shorter payback period.','D. Re-evaluate using the Profitability Index.'], answer: 'B', explanation: 'Wealth maximization (NPV) is the primary goal in finance.' },
    { id: 276, course: 'FIN313', topic: 'WACC', type: 'objective', difficulty: 'hard', question: 'If a company marginal tax rate increases, how does this typically affect its Weighted Average Cost of Capital (WACC)?', options: ['A. WACC increases because taxes are a cost.','B. WACC decreases because the after-tax cost of debt falls.','C. WACC remains unchanged as equity is unaffected.','D. WACC becomes zero.'], answer: 'B', explanation: 'Interest is tax-deductible; higher taxes mean a bigger tax shield on debt.' },
    { id: 277, course: 'BUA399', topic: 'Measurement Levels', type: 'objective', difficulty: 'hard', question: 'Which level of measurement is required to perform operations like Mean and Standard Deviation reliably?', options: ['A. Nominal','B. Ordinal','C. Interval/Ratio','D. Dichotomous'], answer: 'C', explanation: 'Nominal and Ordinal lack equal intervals between points, making means misleading.' },
    { id: 278, course: 'BUA399', topic: 'Internal Validity', type: 'objective', difficulty: 'hard', question: 'History as a threat to internal validity occurs when:', options: ['A. The researcher records the wrong date.','B. An external event happens during the study that affects the results.','C. The participants grow older during the study.','D. The data collection takes too long.'], answer: 'B', explanation: 'History refers to external context shifts during an experiment.' },
];

const appPath = 'src/App.jsx';
let content = fs.readFileSync(appPath, 'utf8');

const trickyStr = trickyQuestions.map(q => JSON.stringify(q, null, 4)).join(',\n    ');

if (content.includes('id: 266')) {
    const endKey = 'id: 266';
    const insertionPoint = content.indexOf('};', content.indexOf(endKey)) + 2;
    if (insertionPoint !== -1) {
        content = content.substring(0, insertionPoint) + ',\n    ' + trickyStr + content.substring(insertionPoint);
        fs.writeFileSync(appPath, content);
        console.log('Injected ' + trickyQuestions.length + ' questions');
    }
}
